import jsPDF from 'jspdf';
import type { Note, Account, Todo } from './api';

interface ExportData {
  note: Note;
  account?: Account;
  todos?: Todo[];
}

export async function generateNotePDF(data: ExportData, type: 'full' | 'minimal'): Promise<void> {
  const { note, account, todos } = data;
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let y = margin;

  // Helper to add text with word wrap
  function addText(text: string, fontSize: number, isBold: boolean = false, color: number[] = [0, 0, 0]) {
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', isBold ? 'bold' : 'normal');
    pdf.setTextColor(color[0], color[1], color[2]);
    const lines = pdf.splitTextToSize(text, contentWidth);
    
    // Check if we need a new page
    const lineHeight = fontSize * 0.5;
    if (y + lines.length * lineHeight > pdf.internal.pageSize.getHeight() - margin) {
      pdf.addPage();
      y = margin;
    }
    
    pdf.text(lines, margin, y);
    y += lines.length * lineHeight + 4;
  }

  function addSectionHeader(text: string) {
    y += 6;
    pdf.setDrawColor(200, 200, 200);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 8;
    addText(text, 14, true, [59, 130, 246]);
  }

  // Title
  addText(note.title, 24, true);
  y += 4;

  // Account info
  if (account) {
    addText(account.name, 12, false, [100, 100, 100]);
  }

  // Meeting date
  if (note.meeting_date) {
    const date = new Date(note.meeting_date).toLocaleDateString('en-US', {
      weekday: 'long',
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    });
    addText(`Meeting: ${date}`, 10, false, [120, 120, 120]);
  }

  // Template type badge
  addText(`Template: ${note.template_type === 'initial' ? 'Initial Call' : 'Follow-up'}`, 10, false, [120, 120, 120]);

  // Full export includes all details
  if (type === 'full') {
    // Account Details
    if (account) {
      addSectionHeader('Account Details');
      
      const accountInfo = [
        `Account Owner: ${account.account_owner || 'Not specified'}`,
        `Budget: ${account.budget ? `$${account.budget.toLocaleString()}` : 'Not specified'}`,
        `Est. Engineers: ${account.est_engineers ?? 'Not specified'}`
      ];
      
      accountInfo.forEach(info => {
        addText(info, 11);
      });
    }

    // Participants
    const hasParticipants = (note.internal_participants?.length ?? 0) > 0 || 
                           (note.external_participants?.length ?? 0) > 0;
    
    if (hasParticipants) {
      addSectionHeader('Participants');
      
      if (note.internal_participants && note.internal_participants.length > 0) {
        addText('Internal (Factory):', 11, true);
        note.internal_participants.forEach(p => {
          addText(`  • ${p}`, 10);
        });
        y += 2;
      }
      
      if (note.external_participants && note.external_participants.length > 0) {
        addText('Customer:', 11, true);
        note.external_participants.forEach(p => {
          addText(`  • ${p}`, 10);
        });
      }
    }
  }

  // Notes content
  addSectionHeader('Notes');
  
  // Convert HTML to plain text
  const tempDiv = document.createElement('div');
  tempDiv.innerHTML = note.content || '';
  const plainText = tempDiv.textContent || tempDiv.innerText || 'No content';
  
  addText(plainText, 11);

  // Todos (full export only)
  if (type === 'full' && todos && todos.length > 0) {
    addSectionHeader('Follow-up Items');
    
    todos.forEach(todo => {
      const status = todo.status === 'completed' ? '✓' : 
                     todo.status === 'in_progress' ? '→' : '○';
      const statusText = todo.status.replace('_', ' ');
      addText(`${status} ${todo.title} (${statusText})`, 11);
      
      if (todo.description) {
        addText(`    ${todo.description}`, 10, false, [100, 100, 100]);
      }
      
      if (todo.due_date) {
        const dueDate = new Date(todo.due_date).toLocaleDateString();
        addText(`    Due: ${dueDate}`, 10, false, [100, 100, 100]);
      }
    });
  }

  // Footer
  y = pdf.internal.pageSize.getHeight() - 15;
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  pdf.text(`Generated by Noted on ${new Date().toLocaleString()}`, margin, y);

  // Download
  const filename = `${note.title.replace(/\s+/g, '-').toLowerCase()}-${type}.pdf`;
  pdf.save(filename);
}
